### PR TITLE
fix silly if error. Fixes #10

### LINKED ISSUE #10: seems to be obviously mistake
on impl_unix.go  line:109
`if lfamily != rfamily && lprotocol != rfamily {`

seems should be 
`if lfamily != rfamily && lprotocol != rprotocol {`

### PR DESCRIPTION
**Pull request by jbenet**

### CODE REVIEW

**Comment by jbenet** [comment]
@tomasen @cryptix @whyrusleeping please CR?

**Comment by cryptix** [comment]
LGTM

**Comment by jbenet** [comment]
thanks @cryptix

**Comment by jbenet** [comment]
@whyrusleeping maybe we should pull this into go-ipfs at some point

**Pull request merged**
